// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ONE_TO_ONE;

#nullable disable

namespace MANY_TO_MANY.Migrations
{
    [DbContext(typeof(WORLDDBCONTEXT))]
    [Migration("20240916182416_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ONE_TO_ONE.KİTAP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KitapAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KİTAPLAR");
                });

            modelBuilder.Entity("ONE_TO_ONE.KİTAPYAZAR", b =>
                {
                    b.Property<int>("KİTAPId")
                        .HasColumnType("int");

                    b.Property<int>("YAZARId")
                        .HasColumnType("int");

                    b.HasKey("KİTAPId", "YAZARId");

                    b.HasIndex("YAZARId");

                    b.ToTable("KİTAPYAZAR");
                });

            modelBuilder.Entity("ONE_TO_ONE.YAZAR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("YazarAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("YAZARLAR");
                });

            modelBuilder.Entity("ONE_TO_ONE.KİTAPYAZAR", b =>
                {
                    b.HasOne("ONE_TO_ONE.KİTAP", "KİTAP")
                        .WithMany("YAZARLAR")
                        .HasForeignKey("KİTAPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ONE_TO_ONE.YAZAR", "YAZAR")
                        .WithMany("KİTAPLAR")
                        .HasForeignKey("YAZARId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KİTAP");

                    b.Navigation("YAZAR");
                });

            modelBuilder.Entity("ONE_TO_ONE.KİTAP", b =>
                {
                    b.Navigation("YAZARLAR");
                });

            modelBuilder.Entity("ONE_TO_ONE.YAZAR", b =>
                {
                    b.Navigation("KİTAPLAR");
                });
#pragma warning restore 612, 618
        }
    }
}
