// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ONE_TO_ONE;

#nullable disable

namespace ONE_TO_ONE.Migrations
{
    [DbContext(typeof(WORLDDBCONTEXT))]
    [Migration("20240916143047_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ONE_TO_ONE.CAPİTAL", b =>
                {
                    b.Property<int>("COUNTRYId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("COUNTRYId");

                    b.ToTable("CAPİTALS");
                });

            modelBuilder.Entity("ONE_TO_ONE.COUNTRY", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("COUNTRIES");
                });

            modelBuilder.Entity("ONE_TO_ONE.CAPİTAL", b =>
                {
                    b.HasOne("ONE_TO_ONE.COUNTRY", "COUNTRY")
                        .WithOne("CAPİTAL")
                        .HasForeignKey("ONE_TO_ONE.CAPİTAL", "COUNTRYId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("COUNTRY");
                });

            modelBuilder.Entity("ONE_TO_ONE.COUNTRY", b =>
                {
                    b.Navigation("CAPİTAL")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
